# Generated by Django 2.1.3 on 2020-02-16 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wizapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('wizapp', '0002_auto_20200216_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.CharField(default=wizapp.models.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
